// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial


import {HorizontalBox, VerticalBox, Button} from "std-widgets.slint";

export global MainCameraAdapter {
    in_out property <image> video_frame;
}

export component VideoWindow inherits Window {
    preferred-width: 500px;
    preferred-height: 600px;
    title: "GStreamer Video Example";
    in property <image> texture <=> img.source;

    VerticalBox {
        Button { text: "Foo"; }
        img := Image {
            width: 320px;
            height: 200px;
            source: MainCameraAdapter.video_frame;
        }
    }
}


export component OtherWindow inherits Window {
    preferred-width: 500px;
    preferred-height: 600px;
    title: "Other Window";
    HorizontalBox {
        Button { text: "First"; }
        Button { text: "Second"; }
        Button { text: "Third"; }
    }
}